# Generated by Django 4.0.5 on 2022-07-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='about',
            field=models.TextField(default='', max_length=150),
        ),
    ]
